export {
  storageApi,
  filesystemApi,
  permissionsApi,
  sharingApi,
  getShareDownloadUrl,
  getSharePreviewUrl,
  usersApi,
  accessRequestsApi,
  sharedWithMeApi,
  sharedDrivesApi,
  driveReadContent,
  driveReadBytes,
  driveAutosaveEncryptedContent,
  driveCreateEncryptedVersion,
  driveAutosaveEncryptedBytes,
  driveCreateEncryptedVersionBytes,
  driveWriteEncryptedContent,
  commentsApi,
  encryptionApi,
  keyFileApi,
  uploadEncryptedFile,
  downloadAndDecryptFile,
  notificationsApi,
  getNotificationsWsUrl,
  tagsApi,
} from './client';

export type { AutosaveTransport } from './client';

// The only way to write user content into Drive. See the module header for why
// the plaintext helpers this replaced no longer exist.
export {
  MissingEncryptionKeyError,
  isMissingEncryptionKey,
  canEncryptFor,
  mintFileKey,
  requireFileKey,
  uploadDriveFile,
  autosaveEncrypted,
  createEncryptedVersion,
  type UploadDriveFileOptions,
} from './encryptedWrites';

export type {
  FileItem,
  FileInfo,
  CreateFileRequest,
  SetImportMetadataRequest,
  FileListQuery,
  DriveFileType,
  QuotaInfo,
  QuotaRequestItem,
  FileVersionItem,
  ListVersionsResponse,
  ZipEntry,
  ZipContentsResponse,
  Folder,
  FolderContentsResponse,
  StarredContentsResponse,
  FolderCreateRequest,
  FolderUpdateRequest,
  FileUpdateRequest,
  BulkMoveRequest,
  BulkDeleteRequest,
  Shortcut,
  ShortcutCreateRequest,
  ShortcutListResponse,
  PermissionRole,
  ResourceType,
  Permission,
  ListPermissionsResponse,
  GrantPermissionRequest,
  UpdatePermissionRequest,
  ShareLink,
  UpsertShareLinkRequest,
  UpdateShareLinkRequest,
  ResolvedShareLink,
  GuestSessionResponse,
  UserLookup,
  AccessRequest,
  ListAccessRequestsResponse,
  CreateAccessRequestRequest,
  ApproveAccessRequestRequest,
  SharedWithMeResponse,
  CommentReply,
  Comment,
  CommentListResponse,
  TrashFileItem,
  TrashFolderItem,
  TrashContentsResponse,
  SharedDrive,
  SharedDriveListResponse,
  FileKeyResponse,
  SetFileKeyRequest,
  ShareFileKeyRequest,
  ArchivedKey,
  PutKeyFileRequest,
  KeyFileResponse,
  NotificationItem,
  NotificationListResponse,
  Tag,
  ListTagsResponse,
  CreateTagRequest,
  UpdateTagRequest,
  SetFileTagsRequest,
  TaggedFile,
  ListTaggedFilesResponse,
} from './types';
