export {
  storageApi,
  filesystemApi,
  permissionsApi,
  sharingApi,
  getShareDownloadUrl,
  getSharePreviewUrl,
  usersApi,
  accessRequestsApi,
  sharedWithMeApi,
  sharedDrivesApi,
  driveReadContent,
  driveReadBytes,
  driveAutosaveEncryptedContent,
  driveCreateEncryptedVersion,
  driveAutosaveEncryptedBytes,
  driveCreateEncryptedVersionBytes,
  driveWriteEncryptedContent,
  commentsApi,
  encryptionApi,
  keyFileApi,
  uploadEncryptedFile,
  downloadAndDecryptFile,
  notificationsApi,
  getNotificationsWsUrl,
  tagsApi,
} from './client';

export type { AutosaveTransport } from './client';

// The only way to write user content into Drive. See the module header for why
// the plaintext helpers this replaced no longer exist.
export {
  MissingEncryptionKeyError,
  isMissingEncryptionKey,
  canEncryptFor,
  mintFileKey,
  requireFileKey,
  uploadDriveFile,
  autosaveEncrypted,
  createEncryptedVersion,
  type UploadDriveFileOptions,
} from './encryptedWrites';

export type {
  FileItem,
  FileInfo,
  CreateFileRequest,
  SetImportMetadataRequest,
  FileListQuery,
  DriveFileType,
  QuotaInfo,
  QuotaRequestItem,
  FileVersionItem,
  ListVersionsResponse,
  ZipEntry,
  ZipContentsResponse,
  Folder,
  FolderContentsResponse,
  StarredContentsResponse,
  FolderCreateRequest,
  FolderUpdateRequest,
  FileUpdateRequest,
  BulkMoveRequest,
  BulkDeleteRequest,
  Shortcut,
  ShortcutCreateRequest,
  ShortcutListResponse,
  PermissionRole,
  ResourceType,
  Permission,
  ListPermissionsResponse,
  GrantPermissionRequest,
  UpdatePermissionRequest,
  ShareLink,
  UpsertShareLinkRequest,
  UpdateShareLinkRequest,
  ResolvedShareLink,
  GuestSessionResponse,
  UserLookup,
  AccessRequest,
  ListAccessRequestsResponse,
  CreateAccessRequestRequest,
  ApproveAccessRequestRequest,
  SharedWithMeResponse,
  CommentReply,
  Comment,
  CommentListResponse,
  TrashFileItem,
  TrashFolderItem,
  TrashContentsResponse,
  SharedDrive,
  SharedDriveListResponse,
  FileKeyResponse,
  SetFileKeyRequest,
  ShareFileKeyRequest,
  ArchivedKey,
  PutKeyFileRequest,
  KeyFileResponse,
  NotificationItem,
  NotificationListResponse,
  Tag,
  ListTagsResponse,
  CreateTagRequest,
  UpdateTagRequest,
  SetFileTagsRequest,
  TaggedFile,
  ListTaggedFilesResponse,
} from './types';

// Team Spaces (issue #185). Behind the `teamSpaces` feature flag server-side, where a gated-off
// route answers 404 — read the flag before rendering a team surface rather than inferring it from
// a failed request.
export {
  teamsApi,
  buildPageTree,
  flattenPageTree,
  TEAM_ROLES,
  TEAM_ROLE_LABELS,
  TEAM_ROLE_DESCRIPTIONS,
  TEAM_VISIBILITY_DESCRIPTIONS,
} from './teams';

export type {
  Team,
  TeamRole,
  TeamVisibility,
  DiscoverableTeam,
  DiscoverableTeamListResponse,
  TeamJoinRequest,
  JoinRequestStatus,
  JoinRequestListResponse,
  TeamListResponse,
  CreateTeamRequest,
  UpdateTeamRequest,
  TeamMember,
  TeamMemberListResponse,
  TeamPage,
  TeamPageListResponse,
  TeamPageNode,
  CreatePageRequest,
  UpdatePageRequest,
  TeamPageVersion,
  TeamPageVersionListResponse,
  TeamActivityEntry,
  TeamActivityResponse,
  TeamFile,
  TeamFolder,
  TeamLibraryResponse,
  TeamShareRole,
  TeamSharedFile,
  TeamSharedFileListResponse,
  FileTeamShare,
  FileTeamShareListResponse,
  MoveFileIntoTeamResponse,
} from './teams';
