export type FeatureFlags = {
  settingsPage: boolean;
  slidesVideoEmbeds: boolean;
  sheetLiveEmbed: boolean;
  driveAreaDropTarget: boolean;
  colorPickerAlpha: boolean;
  search: boolean;
  sheetsCharts: boolean;
  sheetsChartsPhase2: boolean;
  sheetsChartsPhase5: boolean;
  docsLayoutStructure: boolean;
  docsAdvancedFormatting: boolean;
  docsEditingTools: boolean;
  docsPresence: boolean;
  docsTrackChanges: boolean;
  docsCompare: boolean;
  docsMobileEditor: boolean;
  sheetsConditionalFormatting: boolean;
  docsDistractionFree: boolean;
};
