import type { CanonicalThemeToken, ThemeColorScheme } from '@neutrino/api-themes';

/**
 * Full ~24-token canonical palette for each REAL built-in preset — mirrored
 * exactly from web/packages/tokens/src/colors.css's `:root` / `[data-theme="X"]`
 * blocks (canonical keys only; the mirrored alias vars like `--color-text` /
 * `--color-surface-secondary` are intentionally excluded, matching what
 * `CreateThemeRequest.tokens` expects everywhere else in this feature).
 *
 * Used by ThemeGrid's "Duplicate" action to seed a new custom theme from a
 * built-in preset. `'system'` is a meta-choice, not a real palette, and is
 * deliberately excluded here — it never gets a Duplicate action.
 */
export const BUILTIN_THEME_TOKENS: Record<
  string,
  { colorScheme: ThemeColorScheme; tokens: Record<CanonicalThemeToken, string> }
> = {
  light: {
    colorScheme: 'light',
    tokens: {
      '--color-bg': '#ffffff',
      '--color-bg-subtle': '#f9fafb',
      '--color-surface': '#ffffff',
      '--color-surface-raised': '#f9fafb',
      '--color-surface-overlay': '#ffffff',
      '--color-border': '#e5e7eb',
      '--color-border-strong': '#d1d5db',
      '--color-text-primary': '#111827',
      '--color-text-secondary': '#4b5563',
      '--color-text-muted': '#9ca3af',
      '--color-text-inverse': '#ffffff',
      '--color-text-on-accent': '#ffffff',
      '--color-accent': '#2563eb',
      '--color-accent-hover': '#1d4ed8',
      '--color-accent-subtle': '#eff6ff',
      '--color-accent-text': '#1e40af',
      '--color-success': '#16a34a',
      '--color-success-subtle': '#f0fdf4',
      '--color-warning': '#d97706',
      '--color-warning-subtle': '#fffbeb',
      '--color-error': '#dc2626',
      '--color-error-subtle': '#fef2f2',
      '--color-info': '#0284c7',
      '--color-info-subtle': '#f0f9ff',
    },
  },
  dark: {
    colorScheme: 'dark',
    tokens: {
      '--color-bg': '#0f172a',
      '--color-bg-subtle': '#1e293b',
      '--color-surface': '#1e293b',
      '--color-surface-raised': '#334155',
      '--color-surface-overlay': '#1e293b',
      '--color-border': '#334155',
      '--color-border-strong': '#475569',
      '--color-text-primary': '#f1f5f9',
      '--color-text-secondary': '#94a3b8',
      '--color-text-muted': '#64748b',
      '--color-text-inverse': '#0f172a',
      '--color-text-on-accent': '#ffffff',
      '--color-accent': '#3b82f6',
      '--color-accent-hover': '#60a5fa',
      '--color-accent-subtle': '#1e3a5f',
      '--color-accent-text': '#93c5fd',
      '--color-success': '#22c55e',
      '--color-success-subtle': '#052e16',
      '--color-warning': '#f59e0b',
      '--color-warning-subtle': '#1c1003',
      '--color-error': '#ef4444',
      '--color-error-subtle': '#1c0a0a',
      '--color-info': '#38bdf8',
      '--color-info-subtle': '#082f49',
    },
  },
  glass: {
    colorScheme: 'dark',
    tokens: {
      '--color-bg': '#0e1621',
      '--color-bg-subtle': '#162032',
      '--color-surface': '#1a2840',
      '--color-surface-raised': '#223350',
      '--color-surface-overlay': '#1a2840',
      '--color-border': '#2a4060',
      '--color-border-strong': '#3a5578',
      '--color-text-primary': '#dce8f5',
      '--color-text-secondary': '#8aa8c8',
      '--color-text-muted': '#4a6882',
      '--color-text-inverse': '#0e1621',
      '--color-text-on-accent': '#ffffff',
      '--color-accent': '#38bdf8',
      '--color-accent-hover': '#7dd3fc',
      '--color-accent-subtle': '#0c3050',
      '--color-accent-text': '#7dd3fc',
      '--color-success': '#22c55e',
      '--color-success-subtle': '#052e16',
      '--color-warning': '#f59e0b',
      '--color-warning-subtle': '#1c1003',
      '--color-error': '#ef4444',
      '--color-error-subtle': '#1c0a0a',
      '--color-info': '#38bdf8',
      '--color-info-subtle': '#082f49',
    },
  },
  midnight: {
    colorScheme: 'dark',
    tokens: {
      '--color-bg': '#06060f',
      '--color-bg-subtle': '#0d0d1a',
      '--color-surface': '#10102a',
      '--color-surface-raised': '#18183a',
      '--color-surface-overlay': '#10102a',
      '--color-border': '#22224a',
      '--color-border-strong': '#30306a',
      '--color-text-primary': '#e8e8ff',
      '--color-text-secondary': '#9898c4',
      '--color-text-muted': '#55556a',
      '--color-text-inverse': '#06060f',
      '--color-text-on-accent': '#ffffff',
      '--color-accent': '#818cf8',
      '--color-accent-hover': '#a5b4fc',
      '--color-accent-subtle': '#1e1e4a',
      '--color-accent-text': '#a5b4fc',
      '--color-success': '#22c55e',
      '--color-success-subtle': '#052e16',
      '--color-warning': '#f59e0b',
      '--color-warning-subtle': '#1c1003',
      '--color-error': '#ef4444',
      '--color-error-subtle': '#1c0a0a',
      '--color-info': '#38bdf8',
      '--color-info-subtle': '#082f49',
    },
  },
  beach: {
    colorScheme: 'light',
    tokens: {
      '--color-bg': '#fdf8f0',
      '--color-bg-subtle': '#faf3e8',
      '--color-surface': '#fffcf8',
      '--color-surface-raised': '#f5ede0',
      '--color-surface-overlay': '#fffcf8',
      '--color-border': '#dfc9a8',
      '--color-border-strong': '#c4a67d',
      '--color-text-primary': '#3d2b1f',
      '--color-text-secondary': '#7a5c47',
      '--color-text-muted': '#b89a80',
      '--color-text-inverse': '#ffffff',
      '--color-text-on-accent': '#ffffff',
      '--color-accent': '#0ea5e9',
      '--color-accent-hover': '#0284c7',
      '--color-accent-subtle': '#e0f2fe',
      '--color-accent-text': '#0369a1',
      '--color-success': '#16a34a',
      '--color-success-subtle': '#dcfce7',
      '--color-warning': '#d97706',
      '--color-warning-subtle': '#fef3c7',
      '--color-error': '#dc2626',
      '--color-error-subtle': '#fee2e2',
      '--color-info': '#0284c7',
      '--color-info-subtle': '#e0f2fe',
    },
  },
  forest: {
    colorScheme: 'dark',
    tokens: {
      '--color-bg': '#1a2416',
      '--color-bg-subtle': '#202d1c',
      '--color-surface': '#263020',
      '--color-surface-raised': '#2e3d28',
      '--color-surface-overlay': '#263020',
      '--color-border': '#3d5234',
      '--color-border-strong': '#4e6843',
      '--color-text-primary': '#d8e8d0',
      '--color-text-secondary': '#8aaa7e',
      '--color-text-muted': '#4e6843',
      '--color-text-inverse': '#1a2416',
      '--color-text-on-accent': '#052e16',
      '--color-accent': '#4ade80',
      '--color-accent-hover': '#86efac',
      '--color-accent-subtle': '#14532d',
      '--color-accent-text': '#86efac',
      '--color-success': '#4ade80',
      '--color-success-subtle': '#14532d',
      '--color-warning': '#f59e0b',
      '--color-warning-subtle': '#1c1003',
      '--color-error': '#f87171',
      '--color-error-subtle': '#1c0a0a',
      '--color-info': '#38bdf8',
      '--color-info-subtle': '#082f49',
    },
  },
  'light-glass': {
    colorScheme: 'light',
    tokens: {
      // Solid substitute for colors.css's gradient — Duplicate/custom themes
      // don't support gradient backgrounds (see the plan's "no glass-backdrop/
      // gradient support" decision); this is the gradient's 55% stop, chosen
      // as a representative solid color.
      '--color-bg': '#ede9fe',
      '--color-bg-subtle': 'rgba(241, 245, 255, 0.5)',
      '--color-surface': 'rgba(255, 255, 255, 0.60)',
      '--color-surface-raised': 'rgba(255, 255, 255, 0.82)',
      '--color-surface-overlay': 'rgba(255, 255, 255, 0.92)',
      '--color-border': 'rgba(148, 163, 184, 0.28)',
      '--color-border-strong': 'rgba(100, 116, 139, 0.45)',
      '--color-text-primary': '#1e293b',
      '--color-text-secondary': '#475569',
      '--color-text-muted': '#94a3b8',
      '--color-text-inverse': '#ffffff',
      '--color-text-on-accent': '#ffffff',
      '--color-accent': '#6366f1',
      '--color-accent-hover': '#4f46e5',
      '--color-accent-subtle': 'rgba(99, 102, 241, 0.12)',
      '--color-accent-text': '#4338ca',
      '--color-success': '#16a34a',
      '--color-success-subtle': 'rgba(22, 163, 74, 0.12)',
      '--color-warning': '#d97706',
      '--color-warning-subtle': 'rgba(217, 119, 6, 0.12)',
      '--color-error': '#dc2626',
      '--color-error-subtle': 'rgba(220, 38, 38, 0.12)',
      '--color-info': '#0284c7',
      '--color-info-subtle': 'rgba(2, 132, 199, 0.12)',
    },
  },
  sunbeams: {
    colorScheme: 'light',
    tokens: {
      '--color-bg': '#fdfaf0',
      '--color-bg-subtle': '#faf5e4',
      '--color-surface': '#fffef8',
      '--color-surface-raised': '#fef3c7',
      '--color-surface-overlay': '#fffef8',
      '--color-border': '#fcd34d',
      '--color-border-strong': '#f59e0b',
      '--color-text-primary': '#1c1008',
      '--color-text-secondary': '#78501c',
      '--color-text-muted': '#a8782a',
      '--color-text-inverse': '#ffffff',
      '--color-text-on-accent': '#ffffff',
      '--color-accent': '#d97706',
      '--color-accent-hover': '#b45309',
      '--color-accent-subtle': '#fef3c7',
      '--color-accent-text': '#92400e',
      '--color-success': '#16a34a',
      '--color-success-subtle': '#dcfce7',
      '--color-warning': '#d97706',
      '--color-warning-subtle': '#fef3c7',
      '--color-error': '#dc2626',
      '--color-error-subtle': '#fee2e2',
      '--color-info': '#0284c7',
      '--color-info-subtle': '#e0f2fe',
    },
  },
};
